version: '3.8'

services:

  postgres:
    image: postgres:17
    container_name: yuno-postgres

    environment:
      POSTGRES_DB: yuno_payment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Gautam1234

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  payment-orchestrator:
    build: .

    container_name: payment-orchestrator

    depends_on:
      - postgres

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/yuno_payment
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Gautam1234

    ports:
      - "8080:8080"

volumes:
  postgres_data: